### ISSUE TITLE
AttentiveMNMTFeatures model

### ISSUE THREAD

**Issue by bertanunez** [lium-lst/nmtpytorch#12]
When trying to train an AMNMTF model I get this error:

 File "/home/usuaris/veu/tfgveu12/anaconda/envs/tfg/lib/python3.6/site-packages
/nmtpytorch-1.4.0-py3.6.egg/nmtpytorch/models/amnmtfeats.py", line 85, in encode
    feats = batch['image'].view(
  File "/home/usuaris/veu/tfgveu12/anaconda/envs/tfg/lib/python3.6/collections/_
_init__.py", line 991, in __getitem__
    raise KeyError(key)
KeyError: 'image'

I guess that I am missing something insinde the config file but I don't know what it is.

**Comment by ozancaglayan** [comment]
for the AMNMT model(s) you either need images or features extracted from images.

**Comment by bertanunez** [comment]
Yes, I knew that, but I thought that the way to load the features extracted from images was this:

train_set: {'en': '${root}/train.lc.norm.tok.BPE.en',
            'fr': '${root}/train.lc.norm.tok.BPE.fr',
            'image': '${root}/flickr30k_ResNet50_pool5_train.npy'}

and the same with val_set and tests. This doesn't work so I don't know where I must mention something about the features in the configuration file.

**Comment by ozancaglayan** [comment]
You need to hive the convolutional features to this model and not the `pool5` ones. Other than that, your way of defining the `train_set` seems correct.
