### ISSUE TITLE
Enhancement: tutorials about training on a self-defining datasets

### ISSUE THREAD

**Issue by jinfagang** [lium-lst/nmtpytorch#21]
Thanks for this wonderful library, but it would be much more intuitive for users to get started by providing some simple but clearly training process on self-defined dataset.

**Comment by ozancaglayan** [comment]
Hello,

thank you! Do you mean something different than the recent examples:
 https://github.com/lium-lst/nmtpytorch/tree/master/examples/v4.0.0
