### ISSUE TITLE
error when trying the example

### ISSUE THREAD

**Issue by hsuanlyh1997** [lium-lst/nmtpytorch#22]
When I run mmt-task-en-fr-encdecinit.conf I get this error and I don't know how to solve it. 
Could you help me?

  File "/home/ew/.conda/envs/nmtpy/bin/nmtpy", line 145, in <module>
    model = getattr(models, opts.train['model_type'])(opts=opts)
AttributeError: module 'nmtpytorch.models' has no attribute 'MultimodalNMT'

**Comment by xiang-xiang-zhu** [comment]
hello,How did you solve it
