### ISSUE TITLE
How2 Run?

### ISSUE THREAD

**Issue by Eurus-Holmes** [lium-lst/nmtpytorch#26]
From [how2-dataset](https://github.com/srvk/how2-dataset) README.md, 

# How2 Run
> *The results in the dataset paper can be reproduced using [nmtpytorch](https://github.com/lium-lst/nmtpytorch). We provide instructions and configuration files to reproduce three baselines on multi-modal speech-to-text, multi-modal machine translation, and multi-modal summarization.*

But I cannot find any instructions and configuration files, could you update README.md instructions in [nmtpytorch](https://github.com/lium-lst/nmtpytorch) or [how2-dataset](https://github.com/srvk/how2-dataset)?

**Comment by ozancaglayan** [comment]
this is now available in how2 repository.
