### ISSUE TITLE
Error when trying example

### ISSUE THREAD

**Issue by xiang-xiang-zhu** [lium-lst/nmtpytorch#29]
evaluator.py", line 14, in __init__
    self.refs = list(refs.parent.glob(refs.name))
AttributeError: 'str' object has no attribute 'parent'

when i trying use mmt-task-en-fr-nmt.conf,the error occurs

**Comment by xiang-xiang-zhu** [comment]
well,I'm using cu11+pytorch1.8,I don't know the reason for this

**Comment by ozancaglayan** [comment]
Hi,

did you change the paths to correct paths on your machine?

**Comment by xiang-xiang-zhu** [comment]
Yes, I set up a save folder as the save path, then downloaded the multi-30k dataset and took the tok in the task1 folder as the path

**Comment by xiang-xiang-zhu** [comment]
> Hi,
> 
> did you change the paths to correct paths on your machine?

Yes, I build a save folder as the save path, then downloaded the multi-30k dataset and took the tok in the task1 folder as the path

**Comment by xiang-xiang-zhu** [comment]
> Hi,
> 
> did you change the paths to correct paths on your machine?

I checked refs and printed it out. In the mainloop file, you can see that refs is task1/tok/val.lc.norm.tok.fr，and its type is str
