### ISSUE TITLE
Error when trying to start training

### ISSUE THREAD

**Issue by bertanunez** [lium-lst/nmtpytorch#7]
When I run the configuration file I get this error and i don't know how to solve it. Could you help me?

Traceback (most recent call last):
  File "/nmtpytorch/pytorch/bin/nmtpy", line 6, in <mo\
dule>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/nmtpytorch/bin/nmtpy", line 120, in <module>
    model = getattr(models, opts.train['model_type'])(opts=opts, logger=log)
  File "/nmtpytorch/nmtpytorch/models/nmt.py", line 44\
, in __init__
    self.vocabs[lang] = Vocabulary(opts.vocabulary[lang])
  File "nmtpytorch/nmtpytorch/vocabulary.py", line 29\
, in __init__
    self._map = json.load(open(self.vocab))
  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ozancaglayan** [comment]
Hello,

Which configuration did you use? Can you send the `[vocabulary]` section of it?

**Comment by bertanunez** [comment]
[vocabulary]
en: ~/nmtpytorch/dataset-master/scripts/subword-nmt/vocab.en
fr: ~/nmtpytorch/dataset-master/scripts/subword-nmt/vocab.fr

vocab.en and vocab.fr are the vocabulary files created with learn_joint_bpe_and_vocab.py from the subword-nmt repository.

**Comment by ozancaglayan** [comment]
Once you apply subword to your files, you need to use `nmtpy-build-vocab` to create nmtpytorch specific vocab ones. So the vocabulary files in our case are the ones produced with `nmtpy-build-vocab` not the subword vocab files.

**Comment by bertanunez** [comment]
Thank you Ozan!

Now I have another problem using nmtpy-build-vocab. Which are the files (sentene files) arguments?

**Comment by ozancaglayan** [comment]
Those are the training data files for which you want to generate the vocabulary files.

Assuming you applied BPE over your training data and now you have 2 files: `train.bpe.en` and `train.bpe.tr`.

Calling `nmtpy-build-vocab train.bpe.en train.bpe.de` will produce 2 vocabulary files (in .json format) that you should give to the NMT model in the configuration file.

**Comment by bertanunez** [comment]
If I get an error related to Cuda means that I have installed wrong something? I get this error:

File "nmtpytorch/pytorch/lib/python3.5/site-pa\
ckages/torch/cuda/__init__.py", line 55, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by ozancaglayan** [comment]
yes probably you have a problem in your installation :/

Why do you have a `pytorch` folder inside `nmtpytorch`?

I suggest you to install Anaconda with Python 3.6 and then get the pip package of pytorch from pytorch.org which contains the required CUDA libraries inside. Make sure to pick a correct CUDA version. This depends on the nvidia driver installed in your system.

**Comment by bertanunez** [comment]
I know that I have a lot of problems but I have fixed the ones related to the installation. The config file stills doesn't work.

Traceback (most recent call last):
  File "/anaconda/bin/nmtpy", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/nmtpytorch/bin/nmtpy", line 130, in <module>
    model = getattr(models, opts.train['model_type'])(opts=opts, logger=log)
  File "/nmtpytorch/nmtpytorch/models/nmt.py", line 42
, in __init__
    self.vocabs[name] = Vocabulary(fname, name=name)
  File "/nmtpytorch/nmtpytorch/vocabulary.py", line 25
, in __init__
    self._map = json.load(open(self.vocab))
IsADirectoryError: [Errno 21] Is a directory: '.'
