### ISSUE TITLE
Unchanged training result

### ISSUE THREAD

**Issue by sampalomad** [lium-lst/nmtpytorch#9]
Hi, I trained and test the mnmt Greman model on Multi30K several times, but every training test gave me the same BLEU precise to 0.001, and there is no fluctuation in train_loss after at any given epoch across these training logs (for example, the loss after epoch 28 is the same across all 5 training logs),  is it normal?

**Comment by sampalomad** [comment]
Hi, 

yes, the seed is set to 1234

**Comment by ozancaglayan** [comment]
That is the reason. Same seed will produce same results. You can set it 0 for random seeds.

**Comment by sampalomad** [comment]
Thanks a lot!
